//! VC-Plugin CLI 适配器 — 把 CLI 二进制包装成 VcPlugin trait
//!
//! 核心思路（沿用 Python 实现 `vc_plugins.py` 的协议）：
//!   1. 把 input AudioBuffer 编码为 WAV 写入临时文件
//!   2. 构建命令行：binary_path input.wav output.wav --param1 value1 ...
//!   3. 通过 subprocess 调用 CLI
//!   4. 解码 output.wav 到 output AudioBuffer
//!   5. 超时保护：5秒超时，防止卡死
//!
//! # CLI 路径解析优先级
//!
//! 1. 环境变量 `VC_{NAME}_CLI`（如 `VC_REVERB_CLI`）
//! 2. 默认搜索目录 `$VC_AUDIOFX_DIR` 下的 `VC-{Name}/VC-{Name}-CLI-Standalone`
//! 3. 回退到 `/tmp/AudioFX`
//!
//! # 支持26个VC插件
//!
//! Gen1(16): VC-EQ, VC-Comp, VC-Gain, VC-DeEsser, VC-Saturator,
//!           VC-Limiter, VC-Delay, VC-Reverb, VC-DynamicEQ, VC-Smooth,
//!           VC-SurgicalDeEsser, VC-Distortion, VC-Noise, VC-Tune,
//!           VC-Gate, VC-Chorus
//! Gen2(4):  VC-Stereo, VC-PitchShift, VC-MultiBand, VC-Harmonizer
//! 乐器(3):  (待确认具体名称，通过scan自动发现)
//! 其他(3):  (待确认，通过scan自动发现)

use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use opendaw_extension::{AudioBuffer, ParamInfo, PluginError, PluginType, VcPlugin};

// ── 常量 ──────────────────────────────────────────────────────────────────

/// CLI 调用超时（毫秒），防止卡死
#[allow(dead_code)]
const PROCESS_TIMEOUT_MS: u64 = 5000;

/// 目录扫描时匹配的文件名模式
const CLI_BINARY_PATTERN: &str = "CLI-Standalone";

// ── 内置参数映射 ──────────────────────────────────────────────────────────

/// 单个插件的参数定义
struct BuiltinParam {
    id: &'static str,
    name: &'static str,
    cli_flag: &'static str,
    min: f64,
    max: f64,
    default: f64,
    unit: &'static str,
}

/// 所有已知插件的参数定义 + CLI二进制相对路径
struct BuiltinPluginDef {
    plugin_id: &'static str,
    cli_relpath: &'static str,
    params: &'static [BuiltinParam],
}

/// 内置插件定义表 — 沿用 Python 实现 `_VC_CLI_DEFAULTS` 和 `_PARAM_MAPS`
/// 并补充了完整的参数范围信息（min/max/default/unit）
static BUILTIN_PLUGINS: &[BuiltinPluginDef] = &[
    // ── Gen1: 16个效果器 ─────────────────────────────────────────
    BuiltinPluginDef {
        plugin_id: "vc-eq",
        cli_relpath: "VC-EQ/VC-EQ-CLI-Standalone",
        params: &[
            BuiltinParam {
                id: "low_cut",
                name: "Low Cut",
                cli_flag: "--low-cut",
                min: 20.0,
                max: 20000.0,
                default: 20.0,
                unit: "Hz",
            },
            BuiltinParam {
                id: "high_cut",
                name: "High Cut",
                cli_flag: "--high-cut",
                min: 20.0,
                max: 20000.0,
                default: 20000.0,
                unit: "Hz",
            },
            BuiltinParam {
                id: "low_shelf",
                name: "Low Shelf Gain",
                cli_flag: "--low-shelf",
                min: -24.0,
                max: 24.0,
                default: 0.0,
                unit: "dB",
            },
            BuiltinParam {
                id: "high_shelf",
                name: "High Shelf Gain",
                cli_flag: "--high-shelf",
                min: -24.0,
                max: 24.0,
                default: 0.0,
                unit: "dB",
            },
            BuiltinParam {
                id: "peak_freq",
                name: "Peak Frequency",
                cli_flag: "--peak-freq",
                min: 20.0,
                max: 20000.0,
                default: 1000.0,
                unit: "Hz",
            },
            BuiltinParam {
                id: "peak_gain",
                name: "Peak Gain",
                cli_flag: "--peak-gain",
                min: -24.0,
                max: 24.0,
                default: 0.0,
                unit: "dB",
            },
            BuiltinParam {
                id: "peak_q",
                name: "Peak Q",
                cli_flag: "--peak-q",
                min: 0.1,
                max: 30.0,
                default: 1.0,
                unit: "",
            },
        ],
    },
    BuiltinPluginDef {
        plugin_id: "vc-comp",
        cli_relpath: "VC-Comp/VC-Comp-CLI-Standalone",
        params: &[
            BuiltinParam {
                id: "threshold",
                name: "Threshold",
                cli_flag: "--threshold",
                min: -60.0,
                max: 0.0,
                default: -20.0,
                unit: "dB",
            },
            BuiltinParam {
                id: "ratio",
                name: "Ratio",
                cli_flag: "--ratio",
                min: 1.0,
                max: 20.0,
                default: 4.0,
                unit: ":1",
            },
            BuiltinParam {
                id: "attack",
                name: "Attack",
                cli_flag: "--attack",
                min: 0.1,
                max: 100.0,
                default: 10.0,
                unit: "ms",
            },
            BuiltinParam {
                id: "release",
                name: "Release",
                cli_flag: "--release",
                min: 10.0,
                max: 1000.0,
                default: 100.0,
                unit: "ms",
            },
            BuiltinParam {
                id: "makeup",
                name: "Makeup Gain",
                cli_flag: "--makeup",
                min: 0.0,
                max: 24.0,
                default: 0.0,
                unit: "dB",
            },
        ],
    },
    BuiltinPluginDef {
        plugin_id: "vc-gain",
        cli_relpath: "VC-Gain/VC-Gain-CLI-Standalone",
        params: &[BuiltinParam {
            id: "gain",
            name: "Gain",
            cli_flag: "--gain",
            min: -60.0,
            max: 60.0,
            default: 0.0,
            unit: "dB",
        }],
    },
    BuiltinPluginDef {
        plugin_id: "vc-deesser",
        cli_relpath: "VC-DeEsser/VC-DeEsser-CLI-Standalone",
        params: &[
            BuiltinParam {
                id: "threshold",
                name: "Threshold",
                cli_flag: "--threshold",
                min: -60.0,
                max: 0.0,
                default: -30.0,
                unit: "dB",
            },
            BuiltinParam {
                id: "reduction",
                name: "Reduction",
                cli_flag: "--reduction",
                min: 0.0,
                max: 24.0,
                default: 6.0,
                unit: "dB",
            },
            BuiltinParam {
                id: "frequency",
                name: "Frequency",
                cli_flag: "--frequency",
                min: 2000.0,
                max: 12000.0,
                default: 6000.0,
                unit: "Hz",
            },
        ],
    },
    BuiltinPluginDef {
        plugin_id: "vc-saturator",
        cli_relpath: "VC-Saturator/VC-Saturator-CLI-Standalone",
        params: &[
            BuiltinParam {
                id: "drive",
                name: "Drive",
                cli_flag: "--drive",
                min: 0.0,
                max: 100.0,
                default: 30.0,
                unit: "%",
            },
            BuiltinParam {
                id: "mix",
                name: "Mix",
                cli_flag: "--mix",
                min: 0.0,
                max: 100.0,
                default: 50.0,
                unit: "%",
            },
        ],
    },
    BuiltinPluginDef {
        plugin_id: "vc-limiter",
        cli_relpath: "VC-Limiter/VC-Limiter-CLI-Standalone",
        params: &[
            BuiltinParam {
                id: "ceiling",
                name: "Ceiling",
                cli_flag: "--ceiling",
                min: -12.0,
                max: 0.0,
                default: -1.0,
                unit: "dB",
            },
            BuiltinParam {
                id: "release",
                name: "Release",
                cli_flag: "--release",
                min: 10.0,
                max: 1000.0,
                default: 50.0,
                unit: "ms",
            },
        ],
    },
    BuiltinPluginDef {
        plugin_id: "vc-delay",
        cli_relpath: "VC-Delay/VC-Delay-CLI-Standalone",
        params: &[
            BuiltinParam {
                id: "time",
                name: "Delay Time",
                cli_flag: "--time",
                min: 1.0,
                max: 2000.0,
                default: 250.0,
                unit: "ms",
            },
            BuiltinParam {
                id: "feedback",
                name: "Feedback",
                cli_flag: "--feedback",
                min: 0.0,
                max: 100.0,
                default: 30.0,
                unit: "%",
            },
            BuiltinParam {
                id: "mix",
                name: "Mix",
                cli_flag: "--mix",
                min: 0.0,
                max: 100.0,
                default: 30.0,
                unit: "%",
            },
        ],
    },
    BuiltinPluginDef {
        plugin_id: "vc-reverb",
        cli_relpath: "VC-Reverb/VC-Reverb-CLI-Standalone",
        params: &[
            BuiltinParam {
                id: "room",
                name: "Room Size",
                cli_flag: "--room",
                min: 0.0,
                max: 100.0,
                default: 30.0,
                unit: "%",
            },
            BuiltinParam {
                id: "decay",
                name: "Decay",
                cli_flag: "--decay",
                min: 0.0,
                max: 100.0,
                default: 35.0,
                unit: "%",
            },
            BuiltinParam {
                id: "damping",
                name: "Damping",
                cli_flag: "--damping",
                min: 0.0,
                max: 100.0,
                default: 50.0,
                unit: "%",
            },
            BuiltinParam {
                id: "mix",
                name: "Mix",
                cli_flag: "--mix",
                min: 0.0,
                max: 100.0,
                default: 20.0,
                unit: "%",
            },
            BuiltinParam {
                id: "predelay",
                name: "Pre-delay",
                cli_flag: "--predelay",
                min: 0.0,
                max: 100.0,
                default: 0.0,
                unit: "ms",
            },
            BuiltinParam {
                id: "wetlpf",
                name: "Wet LPF",
                cli_flag: "--wetlpf",
                min: 100.0,
                max: 20000.0,
                default: 8000.0,
                unit: "Hz",
            },
        ],
    },
    BuiltinPluginDef {
        plugin_id: "vc-dynamiceq",
        cli_relpath: "VC-DynamicEQ/VC-DynamicEQ-CLI-Standalone",
        params: &[
            BuiltinParam {
                id: "frequency",
                name: "Frequency",
                cli_flag: "--frequency",
                min: 20.0,
                max: 20000.0,
                default: 1000.0,
                unit: "Hz",
            },
            BuiltinParam {
                id: "threshold",
                name: "Threshold",
                cli_flag: "--threshold",
                min: -60.0,
                max: 0.0,
                default: -20.0,
                unit: "dB",
            },
            BuiltinParam {
                id: "q",
                name: "Q",
                cli_flag: "--q",
                min: 0.1,
                max: 30.0,
                default: 1.0,
                unit: "",
            },
            BuiltinParam {
                id: "attack",
                name: "Attack",
                cli_flag: "--attack",
                min: 0.1,
                max: 100.0,
                default: 10.0,
                unit: "ms",
            },
            BuiltinParam {
                id: "release",
                name: "Release",
                cli_flag: "--release",
                min: 10.0,
                max: 1000.0,
                default: 100.0,
                unit: "ms",
            },
        ],
    },
    BuiltinPluginDef {
        plugin_id: "vc-smooth",
        cli_relpath: "VC-Smooth/VC-Smooth-CLI-Standalone",
        params: &[BuiltinParam {
            id: "amount",
            name: "Amount",
            cli_flag: "--amount",
            min: 0.0,
            max: 100.0,
            default: 50.0,
            unit: "%",
        }],
    },
    BuiltinPluginDef {
        plugin_id: "vc-surgicaldeesser",
        cli_relpath: "VC-SurgicalDeEsser/VC-SurgicalDeEsser-CLI-Standalone",
        params: &[
            BuiltinParam {
                id: "threshold",
                name: "Threshold",
                cli_flag: "--threshold",
                min: -60.0,
                max: 0.0,
                default: -30.0,
                unit: "dB",
            },
            BuiltinParam {
                id: "reduction",
                name: "Reduction",
                cli_flag: "--reduction",
                min: 0.0,
                max: 24.0,
                default: 6.0,
                unit: "dB",
            },
            BuiltinParam {
                id: "frequency",
                name: "Frequency",
                cli_flag: "--frequency",
                min: 2000.0,
                max: 12000.0,
                default: 6000.0,
                unit: "Hz",
            },
        ],
    },
    BuiltinPluginDef {
        plugin_id: "vc-distortion",
        cli_relpath: "VC-Distortion/VC-Distortion-CLI-Standalone",
        params: &[
            BuiltinParam {
                id: "mode",
                name: "Mode",
                cli_flag: "--mode",
                min: 0.0,
                max: 5.0,
                default: 0.0,
                unit: "",
            },
            BuiltinParam {
                id: "drive",
                name: "Drive",
                cli_flag: "--drive",
                min: 0.0,
                max: 100.0,
                default: 50.0,
                unit: "%",
            },
            BuiltinParam {
                id: "mix",
                name: "Mix",
                cli_flag: "--mix",
                min: 0.0,
                max: 100.0,
                default: 50.0,
                unit: "%",
            },
        ],
    },
    BuiltinPluginDef {
        plugin_id: "vc-noise",
        cli_relpath: "VC-Noise/VC-Noise-CLI-Standalone",
        params: &[
            BuiltinParam {
                id: "type",
                name: "Noise Type",
                cli_flag: "--type",
                min: 0.0,
                max: 3.0,
                default: 0.0,
                unit: "",
            },
            BuiltinParam {
                id: "level",
                name: "Level",
                cli_flag: "--level",
                min: -60.0,
                max: 0.0,
                default: -30.0,
                unit: "dB",
            },
        ],
    },
    BuiltinPluginDef {
        plugin_id: "vc-tune",
        cli_relpath: "VC-Tune/VC-Tune-CLI-Standalone",
        params: &[
            BuiltinParam {
                id: "speed",
                name: "Speed",
                cli_flag: "--speed",
                min: 0.0,
                max: 100.0,
                default: 50.0,
                unit: "%",
            },
            BuiltinParam {
                id: "scale",
                name: "Scale",
                cli_flag: "--scale",
                min: 0.0,
                max: 24.0,
                default: 0.0,
                unit: "",
            },
            BuiltinParam {
                id: "transpose",
                name: "Transpose",
                cli_flag: "--transpose",
                min: -24.0,
                max: 24.0,
                default: 0.0,
                unit: "st",
            },
            BuiltinParam {
                id: "cents",
                name: "Cents",
                cli_flag: "--cents",
                min: -100.0,
                max: 100.0,
                default: 0.0,
                unit: "cents",
            },
            BuiltinParam {
                id: "formant",
                name: "Formant",
                cli_flag: "--formant",
                min: -12.0,
                max: 12.0,
                default: 0.0,
                unit: "st",
            },
            BuiltinParam {
                id: "autokey",
                name: "Auto Key",
                cli_flag: "--autokey",
                min: 0.0,
                max: 1.0,
                default: 1.0,
                unit: "",
            },
        ],
    },
    BuiltinPluginDef {
        plugin_id: "vc-gate",
        cli_relpath: "VC-Gate/VC-Gate-CLI-Standalone",
        params: &[
            BuiltinParam {
                id: "threshold",
                name: "Threshold",
                cli_flag: "--threshold",
                min: -60.0,
                max: 0.0,
                default: -40.0,
                unit: "dB",
            },
            BuiltinParam {
                id: "ratio",
                name: "Ratio",
                cli_flag: "--ratio",
                min: 1.0,
                max: 20.0,
                default: 10.0,
                unit: ":1",
            },
            BuiltinParam {
                id: "attack",
                name: "Attack",
                cli_flag: "--attack",
                min: 0.1,
                max: 100.0,
                default: 1.0,
                unit: "ms",
            },
            BuiltinParam {
                id: "hold",
                name: "Hold",
                cli_flag: "--hold",
                min: 0.0,
                max: 500.0,
                default: 50.0,
                unit: "ms",
            },
            BuiltinParam {
                id: "release",
                name: "Release",
                cli_flag: "--release",
                min: 10.0,
                max: 1000.0,
                default: 100.0,
                unit: "ms",
            },
            BuiltinParam {
                id: "range",
                name: "Range",
                cli_flag: "--range",
                min: 0.0,
                max: 60.0,
                default: 60.0,
                unit: "dB",
            },
        ],
    },
    BuiltinPluginDef {
        plugin_id: "vc-chorus",
        cli_relpath: "VC-Chorus/VC-Chorus-CLI-Standalone",
        params: &[
            BuiltinParam {
                id: "rate",
                name: "Rate",
                cli_flag: "--rate",
                min: 0.1,
                max: 10.0,
                default: 1.0,
                unit: "Hz",
            },
            BuiltinParam {
                id: "depth",
                name: "Depth",
                cli_flag: "--depth",
                min: 0.0,
                max: 100.0,
                default: 30.0,
                unit: "%",
            },
            BuiltinParam {
                id: "voices",
                name: "Voices",
                cli_flag: "--voices",
                min: 2.0,
                max: 8.0,
                default: 3.0,
                unit: "",
            },
            BuiltinParam {
                id: "mix",
                name: "Mix",
                cli_flag: "--mix",
                min: 0.0,
                max: 100.0,
                default: 50.0,
                unit: "%",
            },
            BuiltinParam {
                id: "delay",
                name: "Delay",
                cli_flag: "--delay",
                min: 0.0,
                max: 50.0,
                default: 10.0,
                unit: "ms",
            },
            BuiltinParam {
                id: "width",
                name: "Width",
                cli_flag: "--width",
                min: 0.0,
                max: 100.0,
                default: 80.0,
                unit: "%",
            },
            BuiltinParam {
                id: "feedback",
                name: "Feedback",
                cli_flag: "--feedback",
                min: 0.0,
                max: 100.0,
                default: 20.0,
                unit: "%",
            },
        ],
    },
    // ── Gen2: 4个新/升级效果器 ───────────────────────────────────
    BuiltinPluginDef {
        plugin_id: "vc-stereo",
        cli_relpath: "VC-Stereo/VC-Stereo-CLI-Standalone",
        params: &[
            BuiltinParam {
                id: "width",
                name: "Width",
                cli_flag: "--width",
                min: 0.0,
                max: 200.0,
                default: 100.0,
                unit: "%",
            },
            BuiltinParam {
                id: "center",
                name: "Center Level",
                cli_flag: "--center",
                min: -60.0,
                max: 0.0,
                default: 0.0,
                unit: "dB",
            },
            BuiltinParam {
                id: "sides",
                name: "Sides Level",
                cli_flag: "--sides",
                min: -60.0,
                max: 0.0,
                default: 0.0,
                unit: "dB",
            },
        ],
    },
    BuiltinPluginDef {
        plugin_id: "vc-pitchshift",
        cli_relpath: "VC-PitchShift/VC-PitchShift-CLI-Standalone",
        params: &[
            BuiltinParam {
                id: "semitones",
                name: "Semitones",
                cli_flag: "--semitones",
                min: -24.0,
                max: 24.0,
                default: 0.0,
                unit: "st",
            },
            BuiltinParam {
                id: "cents",
                name: "Cents",
                cli_flag: "--cents",
                min: -100.0,
                max: 100.0,
                default: 0.0,
                unit: "cents",
            },
            BuiltinParam {
                id: "formant",
                name: "Formant Shift",
                cli_flag: "--formant",
                min: -12.0,
                max: 12.0,
                default: 0.0,
                unit: "st",
            },
            BuiltinParam {
                id: "mode",
                name: "Mode",
                cli_flag: "--mode",
                min: 0.0,
                max: 3.0,
                default: 0.0,
                unit: "",
            },
        ],
    },
    BuiltinPluginDef {
        plugin_id: "vc-multiband",
        cli_relpath: "VC-MultiBand/VC-MultiBand-CLI-Standalone",
        params: &[
            BuiltinParam {
                id: "low_freq",
                name: "Low/Mid Crossover",
                cli_flag: "--low-freq",
                min: 20.0,
                max: 2000.0,
                default: 200.0,
                unit: "Hz",
            },
            BuiltinParam {
                id: "mid_freq",
                name: "Mid/High Crossover",
                cli_flag: "--mid-freq",
                min: 2000.0,
                max: 20000.0,
                default: 5000.0,
                unit: "Hz",
            },
            BuiltinParam {
                id: "low_gain",
                name: "Low Gain",
                cli_flag: "--low-gain",
                min: -24.0,
                max: 24.0,
                default: 0.0,
                unit: "dB",
            },
            BuiltinParam {
                id: "mid_gain",
                name: "Mid Gain",
                cli_flag: "--mid-gain",
                min: -24.0,
                max: 24.0,
                default: 0.0,
                unit: "dB",
            },
            BuiltinParam {
                id: "high_gain",
                name: "High Gain",
                cli_flag: "--high-gain",
                min: -24.0,
                max: 24.0,
                default: 0.0,
                unit: "dB",
            },
        ],
    },
    BuiltinPluginDef {
        plugin_id: "vc-harmonizer",
        cli_relpath: "VC-Harmonizer/VC-Harmonizer-CLI-Standalone",
        params: &[
            BuiltinParam {
                id: "shift1",
                name: "Voice 1 Shift",
                cli_flag: "--shift1",
                min: -24.0,
                max: 24.0,
                default: 3.0,
                unit: "st",
            },
            BuiltinParam {
                id: "shift2",
                name: "Voice 2 Shift",
                cli_flag: "--shift2",
                min: -24.0,
                max: 24.0,
                default: 7.0,
                unit: "st",
            },
            BuiltinParam {
                id: "mix1",
                name: "Voice 1 Mix",
                cli_flag: "--mix1",
                min: 0.0,
                max: 100.0,
                default: 50.0,
                unit: "%",
            },
            BuiltinParam {
                id: "mix2",
                name: "Voice 2 Mix",
                cli_flag: "--mix2",
                min: 0.0,
                max: 100.0,
                default: 30.0,
                unit: "%",
            },
        ],
    },
    // ── Gen3: Phase Cancel Plugin (内置Rust实现) ─────────────
    BuiltinPluginDef {
        plugin_id: "vc-phase-cancel",
        cli_relpath: "", // 内置实现，无需CLI
        params: &[
            BuiltinParam {
                id: "invert_l",
                name: "反转左声道",
                cli_flag: "--invert-l",
                min: 0.0,
                max: 1.0,
                default: 0.0,
                unit: "",
            },
            BuiltinParam {
                id: "invert_r",
                name: "反转右声道",
                cli_flag: "--invert-r",
                min: 0.0,
                max: 1.0,
                default: 0.0,
                unit: "",
            },
            BuiltinParam {
                id: "phase_rotate_l",
                name: "左声道相位旋转",
                cli_flag: "--phase-rotate-l",
                min: 0.0,
                max: 360.0,
                default: 0.0,
                unit: "°",
            },
            BuiltinParam {
                id: "phase_rotate_r",
                name: "右声道相位旋转",
                cli_flag: "--phase-rotate-r",
                min: 0.0,
                max: 360.0,
                default: 0.0,
                unit: "°",
            },
            BuiltinParam {
                id: "allpass_freq",
                name: "全通频率",
                cli_flag: "--allpass-freq",
                min: 20.0,
                max: 20000.0,
                default: 1000.0,
                unit: "Hz",
            },
            BuiltinParam {
                id: "allpass_q",
                name: "全通Q值",
                cli_flag: "--allpass-q",
                min: 0.1,
                max: 18.0,
                default: 0.707,
                unit: "",
            },
            BuiltinParam {
                id: "allpass_order",
                name: "全通阶数",
                cli_flag: "--allpass-order",
                min: 1.0,
                max: 4.0,
                default: 1.0,
                unit: "",
            },
            BuiltinParam {
                id: "ms_width",
                name: "立体声宽度",
                cli_flag: "--ms-width",
                min: 0.0,
                max: 200.0,
                default: 100.0,
                unit: "%",
            },
            BuiltinParam {
                id: "ms_phase_mid",
                name: "Mid相位旋转",
                cli_flag: "--ms-phase-mid",
                min: 0.0,
                max: 360.0,
                default: 0.0,
                unit: "°",
            },
            BuiltinParam {
                id: "ms_phase_side",
                name: "Side相位旋转",
                cli_flag: "--ms-phase-side",
                min: 0.0,
                max: 360.0,
                default: 0.0,
                unit: "°",
            },
            BuiltinParam {
                id: "auto_align",
                name: "自动对齐",
                cli_flag: "--auto-align",
                min: 0.0,
                max: 1.0,
                default: 0.0,
                unit: "",
            },
            BuiltinParam {
                id: "delay_samples_l",
                name: "左声道延迟",
                cli_flag: "--delay-l",
                min: 0.0,
                max: 4096.0,
                default: 0.0,
                unit: "smp",
            },
            BuiltinParam {
                id: "delay_samples_r",
                name: "右声道延迟",
                cli_flag: "--delay-r",
                min: 0.0,
                max: 4096.0,
                default: 0.0,
                unit: "smp",
            },
            BuiltinParam {
                id: "mix",
                name: "干湿比",
                cli_flag: "--mix",
                min: 0.0,
                max: 100.0,
                default: 100.0,
                unit: "%",
            },
            BuiltinParam {
                id: "balance",
                name: "左右平衡",
                cli_flag: "--balance",
                min: -100.0,
                max: 100.0,
                default: 0.0,
                unit: "%",
            },
            BuiltinParam {
                id: "correlation",
                name: "相位相关度",
                cli_flag: "",
                min: -1.0,
                max: 1.0,
                default: 0.0,
                unit: "",
            },
        ],
    },
];
